name: "Bug report"
description: "Create a report to help us improve"
title: "[Bug]: "
labels: ["bug report"]
body:
  - type: markdown
    attributes:
      value: |
        Please use search before opening an issue to check whether your issue has already been reported and perhaps solved.

        Android versions 5.x and 6.x are not supported anymore. Issues happening on these operating system versions will not be resolved.

        To submit a bug report, fill the form below. Provide as much as possible information about the encountered issue. We may request extended information such as `strace` logs if consider necessary. This will help package maintainers to understand the problem correctly and provide a solution. Make sure that your logs do not leak sensitive information (passwords, API keys, etc). Be patient, do not expect that issue could get resolved immediately.
  - type: textarea
    attributes:
      label: Problem description
      description: |
        A clear and concise description of what the problem is. You may attach the logs, screenshots, screen video recording and whatever else that will help to understand the issue.

        Issues without proper description will be closed without solution.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
  - type: textarea
    attributes:
      label: System information
      description: Provide output of `termux-info` in a Markdown **code block** (\`\`\` ... \`\`\`).
    validations:
      required: true
